spring:
  ai:
    openai:
      api-key: sk-Ej44eCRZESr4WPbF26Ab00Ea7c50461aB496B972C49f0fE6
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
      embedding:
        options:
          model: BAAI/bge-m3
      base-url: https://api.bltapi.top
    
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        database-name: default
        collection-name: document_chunks
        embedding-dimension: 1024
        index-type: IVF_FLAT
        metric-type: COSINE
        initialize-schema: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
    org.example.backend: DEBUG